### ISSUE TITLE
Delegate Building the React Bundle to a Build Server

### ISSUE THREAD

**Issue by morrismukiri** [onaio/ansible-react#10]
By using ansible [delegation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#delegation), we can leave the task of [compiling the react bundle](https://github.com/onaio/ansible-react/blob/c8c27a53d07f2cacd2a24c2c8dada6dae8dc9462/tasks/configure.yml#L17) to another host(preferably the local ansible controller)

To do this we'll have to
- Install node on the host to build the bundle
- Install the node modules in package.json on the build host
- Copy environment variables to the build host
- Build the bundle on the build host
- Copy the output to the remote app server

**Comment by p-netm** [comment]
closed by #14
