### ISSUE TITLE
Make max versioned_list length configurable

### ISSUE THREAD

**Issue by moshthepitt** [onaio/ansible-react#9]
In `cleanup.yml` there is a task named `Remove extra files from app directroy` which removes app versions when the number is greater than 10.  Currently, `10` is hard coded.  We need to make this configurable.

**Comment by moshthepitt** [comment]
Maybe also fix the typo on `directroy`

**Comment by moshthepitt** [comment]
This issue affected the Reveal-frontend deployment last week where the server ran out of space and we had to manually delete some of the old app versioned directories

**Comment by p-netm** [comment]
closed #14
